#pragma once

#define TWILI_RESULT(code) (((code) << 9) | 0xEF)

#define TWILI_ERR_INVALID_NRO TWILI_RESULT(1)
#define TWILI_ERR_NO_CRASHED_PROCESSES TWILI_RESULT(2)
#define TWILI_ERR_RESPONSE_SIZE_MISMATCH TWILI_RESULT(3)
#define TWILI_ERR_FATAL_USB_TRANSFER TWILI_RESULT(4)
#define TWILI_ERR_USB_TRANSFER TWILI_RESULT(5)
#define TWILI_ERR_BAD_REQUEST TWILI_RESULT(6)
