#pragma once

#define TWILI_RESULT(code) (((code) << 9) | 0xEF)

#define TWILI_ERR_PROTOCOL_UNRECOGNIZED_OBJECT TWILI_RESULT(1001)
#define TWILI_ERR_PROTOCOL_UNRECOGNIZED_FUNCTION TWILI_RESULT(1002)
#define TWILI_ERR_PROTOCOL_TRANSFER_ERROR TWILI_RESULT(1003)
